/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coffeeShop

class AppTest {
//    @Test
//    fun testAppHasAGreeting() {
//        val classUnderTest = APP
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}
